### ISSUE TITLE
Proxy issue trying to initialize WakaTime

### ISSUE THREAD

**Issue by ChrispyBites** [wakatime/vscode-wakatime#123]
I can't get past the initialization step.  I have our company's proxy set in the cfg and I've tried running it with no_ssl_verify set to both true and false.  On load, I get this:

```
[Extension Host] [WakaTime] [DEBUG] Downloading wakatime-core...
log.ts:171   ERR unable to verify the first certificate: Error: unable to verify the first certificate
	at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
	at emitNone (events.js:86:13)
	at TLSSocket.emit (events.js:188:7)
	at TLSSocket._finishInit (_tls_wrap.js:610:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
log.ts:171   ERR socket hang up: Error: socket hang up
	at createHangUpError (_http_client.js:302:15)
	at TLSSocket.socketCloseListener (_http_client.js:334:23)
	at emitOne (events.js:101:20)
	at TLSSocket.emit (events.js:191:7)
	at _handle.close (net.js:510:12)
	at Socket.done (_tls_wrap.js:332:7)
	at Object.onceWrapper (events.js:293:19)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at TCP._handle.close [as _onclose] (net.js:510:12)
```

**Comment by alanhamlett** [comment]
Does re-installing the plugin help?

**Comment by alanhamlett** [comment]
Is this still an issue on the latest version?
