### ISSUE TITLE
'Subversion' object has no attribute 'info'

### ISSUE THREAD

**Issue by niderhoff** [wakatime/vscode-wakatime#194]
Hi all,

I am getting this exception which prevents the extension from working currently.

```
WakaTime][ERROR] Traceback (most recent call last):
File "wakatime/main.py", line 64, in execute
File "wakatime/heartbeat.py", line 110, in __init__
File "wakatime/project.py", line 94, in get_project_info
File "wakatime/projects/subversion.py", line 41, in folder
AttributeError: 'Subversion' object has no attribute 'info'
```

I enabled debug mode and here is an excerpt from my log:

```
{"now": "2021/05/18 10:40:49 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327247.491053, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:41:03 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327262.0725288, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:41:26 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327285.545506, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:41:29 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327288.023734, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:41:31 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327290.040929, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:41:53 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327311.249699, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:41:59 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327318.1287549, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:42:15 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327333.9218361, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:42:19 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327337.713968, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:42:24 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327342.991385, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:42:31 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327350.801484, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:42:47 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327366.399952, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:43:04 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327383.1783712, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:43:17 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327396.360428, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:43:20 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327398.793391, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:43:21 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327399.8862898, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:43:52 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327430.404242, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:43:53 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327431.8899388, "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:44:42 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327482.3104498, "caller": "wakatime/main.py", "lineno": 68, "file": "tasks", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
{"now": "2021/05/18 10:44:46 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327485.2952561, "caller": "wakatime/logger.py", "lineno": 56, "file": "/Users/idf/Documents/Projects/spotify_playlist_app/spoti.py", "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:45:23 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327522.94332, "caller": "wakatime/main.py", "lineno": 68, "file": "extensions", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
{"now": "2021/05/18 10:45:25 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327523.6615648, "caller": "wakatime/logger.py", "lineno": 56, "file": "/Users/idf/Documents/Projects/spotify_playlist_app/spoti.py", "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:45:32 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327531.6685581, "caller": "wakatime/logger.py", "lineno": 56, "file": "/Users/idf/.wakatime.log", "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
{"now": "2021/05/18 10:50:11 +0200", "version": "13.0.7", "plugin": "vscode/1.56.2 vscode-wakatime/8.0.0", "time": 1621327810.114079, "caller": "wakatime/logger.py", "lineno": 56, "file": "/Users/idf/.wakatime.log", "level": "ERROR", "message": "Traceback (most recent call last):\n  File \"wakatime/main.py\", line 64, in execute\n  File \"wakatime/heartbeat.py\", line 110, in __init__\n  File \"wakatime/project.py\", line 94, in get_project_info\n  File \"wakatime/projects/subversion.py\", line 41, in folder\nAttributeError: 'Subversion' object has no attribute 'info'\n"}
```

**Comment by alanhamlett** [comment]
If you restart VS Code is it fixed? We recently switched from Python to [Go wakatime-cli](https://github.com/wakatime/wakatime-cli) which probably fixes this for you.

**Comment by alanhamlett** [comment]
Closing this issue, since as of yesterday we no longer use Python wakatime-cli. Updating the extension and restarting VS Code will fix it 😄 

For documentation, the bug is accessing `self.info` in
https://github.com/wakatime/wakatime/blob/e8deb156f1c2d26e5cf874da97f7b4354b3f5d20/wakatime/projects/subversion.py#L40
without properly initializing the `self.info` instance attribute at https://github.com/wakatime/wakatime/blob/e8deb156f1c2d26e5cf874da97f7b4354b3f5d20/wakatime/projects/subversion.py#L96

**Comment by niderhoff** [comment]
> Closing this issue, since as of yesterday we no longer use Python wakatime-cli. Updating the extension and restarting VS Code will fix it 😄
> 
> For documentation, the bug is accessing `self.info` in
> https://github.com/wakatime/wakatime/blob/e8deb156f1c2d26e5cf874da97f7b4354b3f5d20/wakatime/projects/subversion.py#L40
> without properly initializing the `self.info` instance attribute at https://github.com/wakatime/wakatime/blob/e8deb156f1c2d26e5cf874da97f7b4354b3f5d20/wakatime/projects/subversion.py#L96

I am using wakatime extension v.10.0. This is the newest version from the VS Code Extension "store". No update is offered by VS Code to me.

**Comment by alanhamlett** [comment]
Adding this line to your `~/.wakatime.cfg` file then restarting vscode will fix it:

    legacy_python_cli = false
