### ISSUE TITLE
Wakatime stuck at Wakatime Initializing...

### ISSUE THREAD

**Issue by developerpruthvi** [wakatime/vscode-wakatime#35]
After I recently upgraded my VS Code, Wakatime stopped sending heartbeats and is stuck at Wakatime Initializing...

Platform: RHEL 7

**Comment by alanhamlett** [comment]
This is probably related to wakatime/wakatime#111, unless it's still stuck Initializing today?

**Comment by alanhamlett** [comment]
Is this fixed now?

**Comment by developerpruthvi** [comment]
No, I still have the same issue with Atom also now.

**Comment by alanhamlett** [comment]
Following [these instructions](https://github.com/wakatime/vscode-wakatime#troubleshooting) are there any error messages in your VS Code console or `~/.wakatime.log` file?

**Comment by OscarDeDios** [comment]
Hi.

I have the same problem. I'm in a corporate net with proxy, but wakatime for sublime text works well in the same computer and environment.

In the wakatime log I only have sublime text logs.

In the developer tools of VSC I have this message:

socket could not be established, cause=write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:
: Error: tunneling socket could not be established, cause=write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:d:\buildagent\workspace\318698\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:

    at ClientRequest.onError (C:\Users\xxxxx\.vscode\extensions\WakaTime.vscode-wakatime-1.2.1\node_modules\request\node_modules\tunnel-agent\index.js:177:17)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at TLSSocket.socketErrorListener (_http_client.js:358:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:480:13)
    at TLSSocket.Socket._destroy (net.js:521:3)
    at WriteWrap.afterWrite (net.js:815:10)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1306   ERR socket hang up: Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at TLSSocket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:191:7)
    at _handle.close (net.js:510:12)
    at TCP.done [as _onclose] (_tls_wrap.js:332:7)


Thanks.

**Comment by EddyVinck** [comment]
Same here. On Ubuntu 18.04.

**Error 1**
```js
[vscode.git]Error parsing /home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/mime-types/package.json: Unexpected end of JSON input
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
e._doInvokeHandler @ rpcProtocol.ts:261
e._invokeHandler @ rpcProtocol.ts:246
e._receiveRequest @ rpcProtocol.ts:192
e._receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:107
(anonymous) @ rpcProtocol.ts:303
e.fire @ event.ts:140
c @ ipc.net.ts:81
(anonymous) @ ipc.net.ts:108
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
mainThreadExtensionService.ts:44 SyntaxError: Error parsing /home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/mime-types/package.json: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at readPackage (module.js:92:52)
	at tryPackage (module.js:102:13)
	at Function.Module._findPath (module.js:183:20)
	at Function.Module._resolveFilename (module.js:468:25)
	at Function.Module._load (module.js:418:25)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/request/request.js:13:12)
	at Object.<anonymous> (/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/request/request.js:1554:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/request/index.js:143:19)
	at Object.<anonymous> (/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/request/index.js:157:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at /home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/out/extension.js:591:79
	at <anonymous>
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
e._doInvokeHandler @ rpcProtocol.ts:261
e._invokeHandler @ rpcProtocol.ts:246
e._receiveRequest @ rpcProtocol.ts:192
e._receiveOneMessage @ rpcProtocol.ts:174
(anonymous) @ rpcProtocol.ts:107
(anonymous) @ rpcProtocol.ts:303
e.fire @ event.ts:140
c @ ipc.net.ts:81
(anonymous) @ ipc.net.ts:108
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
```

**Error 2**
```js
SyntaxError: Error parsing /home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/mime-types/package.json: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at readPackage (module.js:92:52)
	at tryPackage (module.js:102:13)
	at Function.Module._findPath (module.js:183:20)
	at Function.Module._resolveFilename (module.js:468:25)
	at Function.Module._load (module.js:418:25)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/request/request.js:13:12)
	at Object.<anonymous> (/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/request/request.js:1554:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/request/index.js:143:19)
	at Object.<anonymous> (/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/node_modules/request/index.js:157:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.t._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:814:682)
	at Function.o._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:765:373)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/usr/share/code/resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at /home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/out/extension.js:591:79
	at <anonymous>
```

**Error 3**
```js
console.ts:136 [Extension Host] [WakaTime] [ERROR] python3: can't open file '/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/out/wakatime-master/wakatime/cli.py': [Errno 2] No such file or directory
```

**Error 4**
```js
[Extension Host] [WakaTime] [ERROR] Error: Command failed: python3 /home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/out/wakatime-master/wakatime/cli.py --file /home/eddy/Documents/fem/complete-intro-to-react/index.html --plugin vscode/1.25.1 vscode-wakatime/1.2.3 --alternate-project complete-intro-to-react
python3: can't open file '/home/eddy/.vscode/extensions/WakaTime.vscode-wakatime-1.2.3/out/wakatime-master/wakatime/cli.py': [Errno 2] No such file or directory

t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] [WakaTime] [ERROR] Unknown Error (2); Check your /home/eddy/.wakatime.log file for more details.
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
```

**Error 5**
```js
[Extension Host] [WakaTime] [ERROR] Unknown Error (2); Check your /home/eddy/.wakatime.log file for more details.
```

**Log**
File does not exist

Thanks

**Comment by gandarez** [comment]
Is this still happening? @OscarDeDios @EddyVinck

**Comment by OscarDeDios** [comment]
> Is this still happening? @OscarDeDios @EddyVinck

I'm sorry for the delay to answer. I've just checked that it works with my proxy. Thanks!

**Comment by pir4cy** [comment]
I'm on MacOS 10.13.6 and I'm getting the Wakatime initializing error too.
Developer tools show this: 
![image](https://user-images.githubusercontent.com/13626502/88291450-e187c480-cd15-11ea-9fe1-a1847e9157b4.png)

**Comment by Mehr34shad** [comment]
i don't know...


‫‪Kshitij‬‏ <‪notifications@github.com‬‏> در تاریخ پنجشنبه ۲۳ ژوئیهٔ ۲۰۲۰
ساعت ۱۷:۵۴ نوشت:‬

**Comment by pir4cy** [comment]
Got it to work by reinstalling wakatime
removing every instance of wakatime from my machine and installing on vscode first and then sublime
I still haven't tried reinstalling the zsh plugin
