### ISSUE TITLE
Getting SSL Errors since April 6th

### ISSUE THREAD

**Issue by mobychan** [wakatime/vscode-wakatime#51]
Hello,

wakatime in VS Code keeps initializing/working offline/erroring for me since Friday April 6th.
The last Heartbeat that made it to the API seems to be from Friday, 6. April 2018 05:29:28.295 GMT.
I was still working until about 6 hours later and did so today as well but it's still not working.

.wakatime.log has nothing in it for Friday but added this multiple times today:
```{"now": "2018/04/09 08:58:48 Mitteleurop\u00e4ische Sommerzeit", "version": "10.1.3", "plugin": "vscode/1.22.1 vscode-wakatime/1.2.0", "time": 1523257128.693403, "caller": "C:\\Users\\sschewe\\.vscode\\extensions\\WakaTime.vscode-wakatime-1.2\\out\\wakatime-master\\wakatime\\api.py", "lineno": 53, "file": "d:\\MiniProjects\\ColoPix V3\\Assets\\_Frameworks\\BaseClasses\\CustomGUIStyle.cs", "level": "DEBUG", "message": "Sending heartbeats to api at https://api.wakatime.com/api/v1/users/current/heartbeats.bulk"}
{"now": "2018/04/09 08:58:48 Mitteleurop\u00e4ische Sommerzeit", "version": "10.1.3", "plugin": "vscode/1.22.1 vscode-wakatime/1.2.0", "time": 1523257128.693403, "caller": "C:\\Users\\sschewe\\.vscode\\extensions\\WakaTime.vscode-wakatime-1.2\\out\\wakatime-master\\wakatime\\api.py", "lineno": 59, "file": "d:\\MiniProjects\\ColoPix V3\\Assets\\_Frameworks\\BaseClasses\\CustomGUIStyle.cs", "level": "DEBUG", "message": "[{'language': 'C#', 'user_agent': 'wakatime/10.1.3 (Windows-8-6.2.9200) Python3.4.3.final.0 vscode/1.22.1 vscode-wakatime/1.2.0', 'cursorpos': None, 'lines': 39, 'time': 1523257128.693403, 'lineno': None, 'branch': 'master', 'is_write': False, 'entity': 'd:\\\\MiniProjects\\\\ColoPix V3\\\\Assets\\\\_Frameworks\\\\BaseClasses\\\\CustomGUIStyle.cs', 'type': 'file', 'dependencies': ['UnityEngine', 'UnityEditor'], 'project': 'ColoPix V3'}]"}
{"now": "2018/04/09 08:58:50 Mitteleurop\u00e4ische Sommerzeit", "version": "10.1.3", "plugin": "vscode/1.22.1 vscode-wakatime/1.2.0", "time": 1523257128.693403, "caller": "C:\\Users\\sschewe\\.vscode\\extensions\\WakaTime.vscode-wakatime-1.2\\out\\wakatime-master\\wakatime\\api.py", "lineno": 121, "file": "d:\\MiniProjects\\ColoPix V3\\Assets\\_Frameworks\\BaseClasses\\CustomGUIStyle.cs", "level": "WARNING", "message": "{'traceback': 'Traceback (most recent call last):\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\urllib3\\\\connectionpool.py\", line 601, in urlopen\\n    chunked=chunked)\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\urllib3\\\\connectionpool.py\", line 346, in _make_request\\n    self._validate_conn(conn)\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\urllib3\\\\connectionpool.py\", line 850, in _validate_conn\\n    conn.connect()\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\urllib3\\\\connection.py\", line 326, in connect\\n    ssl_context=context)\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\urllib3\\\\util\\\\ssl_.py\", line 329, in ssl_wrap_socket\\n    return context.wrap_socket(sock, server_hostname=server_hostname)\\n  File \"C:\\\\python34\\\\lib\\\\ssl.py\", line 365, in wrap_socket\\n    _context=self)\\n  File \"C:\\\\python34\\\\lib\\\\ssl.py\", line 583, in __init__\\n    self.do_handshake()\\n  File \"C:\\\\python34\\\\lib\\\\ssl.py\", line 810, in do_handshake\\n    self._sslobj.do_handshake()\\nssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\requests\\\\adapters.py\", line 440, in send\\n    timeout=timeout\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\urllib3\\\\connectionpool.py\", line 639, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\urllib3\\\\util\\\\retry.py\", line 388, in increment\\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(SSLError(1, \\'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)\\'),))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\api.py\", line 107, in send_heartbeats\\n    verify=not args.nosslverify)\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\requests\\\\sessions.py\", line 555, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\requests\\\\sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\requests\\\\sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"C:\\\\Users\\\\sschewe\\\\.vscode\\\\extensions\\\\WakaTime.vscode-wakatime-1.2\\\\out\\\\wakatime-master\\\\wakatime\\\\packages\\\\requests\\\\adapters.py\", line 506, in send\\n    raise SSLError(e, request=request)\\nwakatime.packages.requests.exceptions.SSLError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(SSLError(1, \\'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)\\'),))\\n', 'SSLError': \"HTTPSConnectionPool(host='api.wakatime.com', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))\"}"}
```

I tried un-/reinstalling the plugin as well as the newest python version but still can't get it to work.
using debug=true I get this in the Developer Tools in VS Code:

```
[Extension Host] [WakaTime] [DEBUG] Initializing WakaTime v1.2.0
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [DEBUG] Looking for python at: C:\Users\sschewe\.vscode\extensions\WakaTime.vscode-wakatime-1.2.0\out\python\pythonw
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [DEBUG] Looking for python at: pythonw
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [DEBUG] Valid python version: Python 3.6.5

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [DEBUG] Downloading wakatime-core...
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1306   ERR self signed certificate in certificate chain: Error: self signed certificate in certificate chain
	at TLSSocket.<anonymous> (_tls_wrap.js:1088:38)
	at emitNone (events.js:86:13)
	at TLSSocket.emit (events.js:188:7)
	at TLSSocket._finishInit (_tls_wrap.js:610:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1306   ERR socket hang up: Error: socket hang up
	at createHangUpError (_http_client.js:302:15)
	at TLSSocket.socketCloseListener (_http_client.js:334:23)
	at emitOne (events.js:101:20)
	at TLSSocket.emit (events.js:191:7)
	at _handle.close (net.js:510:12)
	at TCP.done [as _onclose] (_tls_wrap.js:332:7)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] ApplicationInsights:Sender Array(1)
t.log @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] ApplicationInsights:Sender Array(1)
t.log @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [DEBUG] Sending heartbeat: pythonw C:\Users\sschewe\.vscode\extensions\WakaTime.vscode-wakatime-1.2.0\out\wakatime-master\wakatime\cli.py --file "d:\MiniProjects\ColoPix V3\Assets\_Frameworks\BaseClasses\CustomGUIStyle.cs" --plugin "vscode/1.22.1 vscode-wakatime/1.2.0" --alternate-project "ColoPix V3" --config C:\Users\sschewe\.wakatime.cfg --logfile C:\Users\sschewe\.wakatime.log
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [ERROR] pythonw: can't open file 'C:\Users\sschewe\.vscode\extensions\WakaTime.vscode-wakatime-1.2.0\out\wakatime-master\wakatime\cli.py': [Errno 2] No such file or directory

t.log @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [ERROR] Error: Command failed: pythonw C:\Users\sschewe\.vscode\extensions\WakaTime.vscode-wakatime-1.2.0\out\wakatime-master\wakatime\cli.py --file d:\MiniProjects\ColoPix V3\Assets\_Frameworks\BaseClasses\CustomGUIStyle.cs --plugin vscode/1.22.1 vscode-wakatime/1.2.0 --alternate-project ColoPix V3 --config C:\Users\sschewe\.wakatime.cfg --logfile C:\Users\sschewe\.wakatime.log
pythonw: can't open file 'C:\Users\sschewe\.vscode\extensions\WakaTime.vscode-wakatime-1.2.0\out\wakatime-master\wakatime\cli.py': [Errno 2] No such file or directory

t.log @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] [WakaTime] [ERROR] Unknown Error (2); Check your C:\Users\sschewe\.wakatime.log file for more details.
t.log @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260
console.ts:136 [Extension Host] ApplicationInsights:Sender [Object]
```
The wakatime-master folder it looks for does not exist, but there's an empty wakatime-master.zip file in the out folder

I'm using VS Code Version 1.22.1 on a Windows 10 and the WakaTime Extension has Version 1.2 (I played around with WakaTime Version 1.1.24 but that didn't help).
Python is now on Version 3.6.5

My company removed the proxy a few weeks back, but wakatime kept working without problems(I checked the Dashboard daily).

Any ideas what could be happening/what I could try to make it work again?

**Comment by alanhamlett** [comment]
Since your company removed it's proxy, you should remove the `proxy` setting in your `~/.wakatime.cfg` file as it's no longer needed.

You can also edit that proxy config within VS Code with `ctrl + shift + p` then `WakaTime Proxy`.

**Comment by mobychan** [comment]
Thank you for your time.

I removed that setting back when the proxy was removed(and it did work for multiple weeks) and I just checked again, the current content of my ~/.wakatime.cfg file looks like this:

```
[settings]
api_key = XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
debug = true
```

----------------------------

would it be possible to copy the .wakatime.db file to another pc to sync the data for now or would that create problems?

**Comment by alanhamlett** [comment]
`~/.wakatime.db` is just an sqlite file, so you can safely copy it to another computer and it will sync. If your first computer gets back online in the future, the duplicate data will be ignored.

**Comment by alanhamlett** [comment]
Just want to check in, is everything working now?

**Comment by mobychan** [comment]
Nope still not working, but it might be an issue with my companies firewall, I have been informed that a lot has been changed and as far as I understand it's messing with the https-certificates by deciphering, analysing and then reencoding the requests.

Not sure if this could help but I started using [this plugin for unity](https://github.com/vladfaust/unity-wakatime) a while ago, which is working just fine, but uses a direct web-api approach it seems.

But copying the .db file at least lets me upload the data from home, even if it took a while for the data to be uploaded

**Comment by alanhamlett** [comment]
Try adding this to your `~/.wakatime.cfg` file:

`no_ssl_verify = true`

**Comment by mobychan** [comment]
**I finally got it working again.**
Looks like the extension is unable to download the wakatime-cli/core correctly and somehow the previously existing one was removed
I downloaded it directly from the github and extracted it into .vscode\extensions\WakaTime.vscode-wakatime-1.2.1\out\
Additionally I updated the plugin by using "Extensions: Check for Updates" because the [status page](https://wakatime.com/plugins/status) told me there was a newer version available(vscode didn't show this) this changed the extensions version from 1.2.0 to 1.2.1

**Comment by alanhamlett** [comment]
That's good! If the VS Code plugin isn't able to download wakatime-cli through the proxy, it might break the next time you upgrade the WakaTime extension for VS Code since wakatime-cli is stored in the plugin's folder and deleted/re-downloaded when a plugin version's folder is removed after upgrading.

Since [v1.1.13](https://github.com/wakatime/vscode-wakatime/blob/master/CHANGELOG.md#1113-2017-08-14) released in 2017 the WakaTime VS Code plugin should be using the proxy value from `~/.wakatime.cfg` when downloading wakatime-cli. If the plugin is sending heartbeats but not able to download/update wakatime-cli then that's a bug that we should fix.

**Comment by alanhamlett** [comment]
Looks like this is the same issue as #11. One fix might be to disable verifying ssl certs, if your proxy is injecting it's own cert.

**Comment by mobychan** [comment]
By disabling verifying ssl certs do you mean using the `no_ssl_verify = true` setting?
Because that did not work.

**Comment by alanhamlett** [comment]
Yep, that would only work if we disable verifying certs in vscode based on that wakatime-cli config.

**Comment by nicholasinatel** [comment]
> 
> 
> **I finally got it working again.**
> Looks like the extension is unable to download the wakatime-cli/core correctly and somehow the previously existing one was removed
> I downloaded it directly from the github and extracted it into .vscode\extensions\WakaTime.vscode-wakatime-1.2.1\out
> Additionally I updated the plugin by using "Extensions: Check for Updates" because the [status page](https://wakatime.com/plugins/status) told me there was a newer version available(vscode didn't show this) this changed the extensions version from 1.2.0 to 1.2.1

@mobychan could you please elaborate more on how you managed to do it, i tried following your steps and still nothing, i copy the github to the out folder but the visual studio code see's my version as 1.2.4 and the status page see's it as 1.2.3. 
Thank you best regards

**Comment by cbb330** [comment]
I also had this issue and can offer a possible solution.

My employer tweaked some setting that disables any default certificate CA trust. So to re-enable the trust needed for NodeJS to download the CLI from Github:

- export Github's root CA certificate in PEM format
- set your environment variable 'NODE_EXTRA_CA_CERTS' to filepath of that exported cert
- reload VSCode

More info on that environment variable here [https://developer.ibm.com/node/2017/03/02/extend-nodes-built-ca-certificate-store-using-node_extra_ca_certs/](url)
