### ISSUE TITLE
Unknown error in VSCode on Ubuntu 18.04

### ISSUE THREAD

**Issue by Kondenko** [wakatime/vscode-wakatime#55]
I've installed this plugin as per the instruction, but instead of logging my activity it gives the following log output:

```
console.ts:136 [Extension Host] [WakaTime] [ERROR] Error: Command failed: python3 /home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/cli.py --file /home/kondenko/Projects/web/cv-kondenko/src/components/introduction/Introduction.vue --plugin vscode/1.23.1 vscode-wakatime/1.2.2 --alternate-project cv-kondenko --write
Traceback (most recent call last):
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/cli.py", line 35, in <module>
    sys.exit(wakatime.execute(sys.argv[1:]))
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/main.py", line 42, in execute
    setup_logging(args, __version__)
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/logger.py", line 81, in setup_logging
    handler = logging.FileHandler(os.path.expanduser(logfile))
  File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/kondenko/.wakatime.log'

t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] [WakaTime] [ERROR] Unknown Error (1); Check your /home/kondenko/.wakatime.log file for more details.
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Sending heartbeat: python3 /home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/cli.py --file /home/kondenko/Projects/web/cv-kondenko/src/components/introduction/Introduction.vue --plugin "vscode/1.23.1 vscode-wakatime/1.2.2" --alternate-project cv-kondenko --write
console.ts:136 [Extension Host] [WakaTime] [ERROR] Traceback (most recent call last):
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/cli.py", line 35, in <module>
    sys.exit(wakatime.execute(sys.argv[1:]))
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/main.py", line 42, in execute
    setup_logging(args, __version__)
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/logger.py", line 81, in setup_logging
    handler = logging.FileHandler(os.path.expanduser(logfile))
  File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/kondenko/.wakatime.log'

t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] [WakaTime] [ERROR] Error: Command failed: python3 /home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/cli.py --file /home/kondenko/Projects/web/cv-kondenko/src/components/introduction/Introduction.vue --plugin vscode/1.23.1 vscode-wakatime/1.2.2 --alternate-project cv-kondenko --write
Traceback (most recent call last):
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/cli.py", line 35, in <module>
    sys.exit(wakatime.execute(sys.argv[1:]))
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/main.py", line 42, in execute
    setup_logging(args, __version__)
  File "/home/kondenko/.vscode/extensions/WakaTime.vscode-wakatime-1.2.2/out/wakatime-master/wakatime/logger.py", line 81, in setup_logging
    handler = logging.FileHandler(os.path.expanduser(logfile))
  File "/usr/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/kondenko/.wakatime.log'

t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:393
(anonymous) @ extensionHost.ts:210
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
console.ts:136 [Extension Host] [WakaTime] [ERROR] Unknown Error (1); Check your /home/kondenko/.wakatime.log file for more details.
```

**Comment by Kondenko** [comment]
Thanks for pointing that out, I ran `sudo chmod 777 /home/kondenko/.wakatime.log` and it's working now.
