### ISSUE TITLE
stuck at installing wakatime plugin in vscode 

### ISSUE THREAD

**Issue by Nourahussein** [wakatime/vscode-wakatime#63]
I'm trying to install wakatime  inside vscode but it keeps installing and nothing happens after that ![image](https://s33.postimg.cc/q0o30km73/Screenshot_from_2018-09-03_16-03-47.png)

**Comment by alanhamlett** [comment]
Are there some error messages in your Developer Console window? The most likely cause is a networking problem, but the console messages should tell the exact reason:
https://github.com/wakatime/vscode-wakatime#troubleshooting

**Comment by Nourahussein** [comment]
here's the error 
![here](https://s22.postimg.cc/3xvcza2ch/Screenshot_from_2018-09-04_10-02-05.png)

**Comment by alanhamlett** [comment]
Those errors are unrelated to WakaTime. Can you try re-installing the WakaTime plugin with the Developer Console open and see if any errors appear when installing?

**Comment by astaruch** [comment]
Hi, I have the same issue. There is following error message:

```
[Extension Host] [WakaTime] [DEBUG] Initializing WakaTime v1.2.3
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Looking for python at: python3
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Invalid python version: 
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Looking for python at: pythonw
console.ts:136 [Extension Host] [WakaTime] [DEBUG] Valid python version: Python 3.7.0

console.ts:136 [Extension Host] [WakaTime] [DEBUG] Downloading wakatime-core...
log.ts:171   ERR self signed certificate in certificate chain: Error: self signed certificate in certificate chain
	at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
	at emitNone (events.js:106:13)
	at TLSSocket.emit (events.js:208:7)
	at TLSSocket._finishInit (_tls_wrap.js:637:8)
	at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
log.ts:171   ERR socket hang up: Error: socket hang up
	at createHangUpError (_http_client.js:331:15)
	at TLSSocket.socketCloseListener (_http_client.js:363:23)
	at emitOne (events.js:121:20)
	at TLSSocket.emit (events.js:211:7)
	at _handle.close (net.js:554:12)
	at TCP.done [as _onclose] (_tls_wrap.js:356:7)
console.ts:136 [Extension Host] [WakaTime] [ERROR] (null): can't open file 'C:\Users\<name>\.vscode\extensions\wakatime.vscode-wakatime-1.2.3\out\wakatime-master\wakatime\cli.py': [Errno 2] No such file or directory

t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] [WakaTime] [ERROR] Error: Command failed: pythonw C:\Users\<name>\.vscode\extensions\wakatime.vscode-wakatime-1.2.3\out\wakatime-master\wakatime\cli.py --file c:\Users\<path to current opened file> --plugin vscode/1.28.1 vscode-wakatime/1.2.3 --alternate-project <name of project>--config C:\Users\<name>\.wakatime.cfg --logfile C:\Users\<name>\.wakatime.log
(null): can't open file 'C:\Users\<name>\.vscode\extensions\wakatime.vscode-wakatime-1.2.3\out\wakatime-master\wakatime\cli.py': [Errno 2] No such file or directory
```

**Comment by Nourahussein** [comment]
@astaruch 
I solved the problem by killall process of vscode 
you can type killall -9 code in terminal or open your Activity Monitor and kill all process related to 'code'
then remove code using those steps:
step1: remove settings and configs
sudo rm -rf $HOME/Library/Application\ Support/Code
step2: remove all the extensions
sudo rm -rf $HOME/.vscode
step3: remove vscode from application
then install vscode again 'stable version' and it will work just fine :100: 
after I wrote all this I figured you are using windows, so the error is unrelated to waktaime itself it all about Vscode.

**Comment by gandarez** [comment]
@alanhamlett may we close this issue?
