### ISSUE TITLE
VSCode not working on Windows

### ISSUE THREAD

**Issue by stijnbuurman** [wakatime/vscode-wakatime#8]
I had to use my windows pc today because I forgot my charger at work. I installed WakaTime for vscode but it didn't ask me for an API key, so obviously it's not working.

this is the output from the console:

```
[Extension Host] Initializing WakaTime v1.0.4
threadService.ts:207[Extension Host] TypeError: Cannot read property 'length' of null
    at writeOrBuffer (_stream_writable.js:268:41)
    at Writable.write (_stream_writable.js:215:11)
    at Object.execFileSync (child_process.js:499:20)
    at Object.module.(anonymous function) [as execFileSync] (ELECTRON_ASAR.js:158:20)
    at Dependencies.getPythonLocation (C:\Users\stijn\.vscode\extensions\WakaTime.vscode-wakatime-1.0.4\out\extension.js:265:44)
    at Dependencies.isPythonInstalled (C:\Users\stijn\.vscode\extensions\WakaTime.vscode-wakatime-1.0.4\out\extension.js:384:14)
    at Dependencies.checkAndInstall (C:\Users\stijn\.vscode\extensions\WakaTime.vscode-wakatime-1.0.4\out\extension.js:182:14)
    at new WakaTime (C:\Users\stijn\.vscode\extensions\WakaTime.vscode-wakatime-1.0.4\out\extension.js:33:27)
    at activate (C:\Users\stijn\.vscode\extensions\WakaTime.vscode-wakatime-1.0.4\out\extension.js:16:20)
    at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:12:438)
threadService.ts:207[Extension Host] Downloading wakatime-core...
threadService.ts:207[Extension Host] Extracting wakatime-core into "C:\Users\stijn\.vscode\extensions\WakaTime.vscode-wakatime-1.0.4\out"...
threadService.ts:207[Extension Host] Finished extracting wakatime-core.
```

**Comment by alanhamlett** [comment]
Looks like it's working, it just found your api key from the common config file in your user home folder.

**Comment by stijnbuurman** [comment]
You are totally right. Does it share my api key between code editors? 
Thanks again.

**Comment by alanhamlett** [comment]
Yes, all plugins share the same config file except for Kodomo, Sublime Text, and Atom. Once we release WakaTime Desktop, even those editors will share the same api key.

**Comment by stijnbuurman** [comment]
That's really nice! Sorry for the false alarm.
